Project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
# import forms_builder.forms.urls
from django.conf import settings
from django.conf.urls.static import static
from jobs import views  # jobs.views
from accounts import views  # accounts.views
from crm.views import MainPage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPage.as_view(), name='mainpage'),
    # path('forms/', include(forms_builder.forms.urls)),
    path('crm/', include('crm.urls', namespace='KMA_CRM')),
    path('blog/', include('blog.urls', namespace='blog')),
    # path('signup/', include('accounts.urls', namespace='accounts')),
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('jobs/', include('jobs.urls', namespace='amr_jobs')),
    path('laundry/', include('laundry.urls', namespace='laundry')),
    path('amrblog/', include('amrblog.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #\
  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from crm import views
from crm.views import *  # HomePage,Search,SaveDone

app_name = "crm"
urlpatterns = [
    path('', views.HomePage, name='home'),
    path('results/', views.Search, name='search'),
    path('registerdata/', views.RegisterData, name='regdata'),
    path('done/', views.SaveDone, name='done'),
    # path('reports/', views.ClientsRport, name='clientreport'),
    path('reports/', ClientsRport.as_view(), name='clientreport'),
    # path('clients/', ClientsListView.as_view(), name='clients'),
    path('clients/edit/', views.EditClients, name='clients_edit'),
    # path('clients/edit/<int:id>/', views.ClientID, name='clients_update'),
    path('clients/edit/<int:id>/',
                views.ClientID, name='clients_update'),
    path('clients/', views.ClientName, name='clients'),
    # path('login/', views.LoginForm, name='login'),
    # path('signup/', views.signup, name='signup'),
    # path('register/', views.user_register, name='user_register'),
    path('record/', views.Firm, name='record_firm'),
    path('record/edit/', views.EditFirm, name='edit'),
    path('record/<int:id>/', views.Firm_Update, name='firm_update'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

laundry/urls.py
from django.urls import path
from .views import laundry_views, search, reports, pdf_files 
                    # (laundrypage,laundry_bill,newitems,additems,
                    # laundry_data,edit_bills,get_single_field,
                    # edit_items,search,delete_item,pass_data,
                    # GeneratePdf, get_pdf, export_table, 
                    # canceled_bill, paid_zero, remain_zero,
                    # calculate_sum, all_remain, daily_reports, 
                    # search_date)
# from .views import (laundrypage,laundry_bill,newitems,additems,
#                     laundry_data,edit_bills,get_single_field,
#                     edit_items,search,delete_item,pass_data,
#                     GeneratePdf, get_pdf, export_table, 
#                     canceled_bill, paid_zero, remain_zero,
#                     calculate_sum, all_remain, daily_reports, 
#                     search_date)

app_name = 'laundry'

urlpatterns = [
    path('', laundry_views.laundrypage, name='home'),
    #
    path('search/date/', search.search_date, name='search_date'),
    #
    path('day/report/', reports.daily_reports, name='daily_reports'),
    #
    path('sum/', reports.calculate_sum, name='calculate_sum'),
    #
    path('zero/paid/', reports.paid_zero, name='paid_zero'),
    #
    path('all/remain/', reports.all_remain, name='all_remain'),
    #
    path('zero/remain/', reports.remain_zero, name='remain_zero'),
    #
    path('canceled/bill/', reports.canceled_bill, name='canceled_bill'),
    #
    path('bill/', laundry_views.laundry_bill, name='bill'),
    #
    path('additem/bill=<int:bill>/', laundry_views.additems, name='additems'),
    #
    path('additem/', laundry_views.newitems, name='newitems'),
    # for add items
    path('<int:bill>/', laundry_views.laundry_data, name='data'),
    # this view was for exprement some features
    path('single/<int:bill>/', laundry_views.get_single_field, name='single_field'),
    # for edit bill (in general)
    path('bill/<int:id>/', laundry_views.edit_bills, name='edit_bills'), 
    # for edit items in every bill
    path('bill=<int:bill>/id=<int:id>/', laundry_views.edit_items, name='edit_items'), 
    #
    path('search/', search.search, name='search'), 
    #
    path('bill/<int:bill>/<int:id>/', laundry_views.delete_item, name='delete_item'), 
    # for passing data from one form to another form
    path('pass/<int:bill>/<int:customer>/<str:ltype>/<int:quantity>/<int:price>/<int:total>/',
        laundry_views.pass_data, name='pass_data'), 

    path('Gpdf/', pdf_files.GeneratePdf.as_view(), name='GeneratePdf'),
    path('pdf/', pdf_files.get_pdf, name='get_Pdf'),

    # for exporting tables2 to another format
    path('exportdata/', pdf_files.export_table, name="export_table"),
]

laundry/views.py
from django.db.models import Count, Sum, Avg, Q
from datetime import date
# from weasyprint import HTML
# from django.db.models.query.RawQuerySet import raw
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.utils.timezone import datetime, now
import time
from .models import LaundryBill, LaundryData, Customers
from crm.models import Clients
from .forms import LaundryBillForm, LaundryDataForm

from crm.tables import LaundryDataTable, LaundryBillTable, SumLaundryBillTable
from django_tables2.config import RequestConfig
from django_tables2.export.export import TableExport

from django.views.generic import View
from django.template.loader import get_template
from Project.utils import render_to_pdf # for Justin code 

#################################################################


# Justin code to render html to pdf
class GeneratePdf(View):
    # def get(self, request, *args, **kwargs):
    #     billtable = LaundryBillTable(LaundryBill.objects.all().order_by('-id'))
    #     template = get_template('laundry/pdf.html')
    #     context = {
    #         "billtable":billtable,
    #         "invoice_id": 123,
    #         "customer_name": "John Cooper",
    #         "amount": 1399.99,
    #         "today": "Today",
    #     }
    #     html = template.render(context)
    #     pdf = render_to_pdf('laundry/pdf.html', context)
    #     if pdf:
    #         response = HttpResponse(pdf, content_type='application/pdf')
    #         filename = "Invoice_%s.pdf" %("12341231")
    #         content = "inline; filename='%s'" %(filename)
    #         download = request.GET.get("download")
    #         if download:
    #             content = "attachment; filename='%s'" %(filename)
    #         response['Content-Disposition'] = content
    #         return response
    #     return HttpResponse(pdf, content_type='application/pdf')

    def get(self, request, *args, **kwargs):
        zero_remain = LaundryBill.objects.filter(sumtotal__gt=0, returns=False, remain=0).order_by('-id')
        template = get_template('laundry/zero_remain.html')
        context = {
            "zero_remain":zero_remain,
        }
        html = template.render(context)
        pdf = render_to_pdf('laundry/zero_remain.html', context)
        if pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            filename = "Invoice_%s.pdf" %("12341231")
            content = "inline; filename='%s'" %(filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" %(filename)
            response['Content-Disposition'] = content
            return response
        return HttpResponse(pdf, content_type='application/pdf')

#This is func based to render to pdf
def get_pdf(request, *args, **kwargs):
    # table = LaundryBillTable(LaundryBill.objects.all().order_by('-id'))
    # table.paginate(page=request.GET.get("page", 1), per_page=15)
    query = LaundryBill.objects.all().order_by('-id')
    zero_remain = LaundryBill.objects.filter(sumtotal__gt=0, returns=False, remain=0).order_by('-id')
     
    # x = remain_zero(request)
    # print(x)
    # billtable = LaundryBillTable(LaundryBill.objects.all()[0:4])
    # print(str(billtable.rows[:]))
    # row_table = ", ".join(map(str, billtable.rows[0]))
    # print(", ".join(map(str, billtable.rows[0])))
    template = get_template('laundry/pdf.html')
    context = {'zero_remain':zero_remain,
        "query":query,
        "invoice_id": 123,
        "customer_name": "John Cooper",
        "amount": 1399.99,
        "today": "Today",
    }
    html = template.render(context)
    pdf = render_to_pdf('laundry/pdf.html', context)
    if pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        filename = "Invoice_"+str(time.strftime('%d-%m-%Y'))+".pdf" #%('%Y-%m-%d')
        content = "inline; filename=%s" %(filename)
        download = request.GET.get("download")
        if download:
            content = "attachment; filename='%s'" %(filename)
        response['Content-Disposition'] = content
        return response
    return HttpResponse(pdf, content_type='application/pdf')

# Export to any kind of document from tables2_Documentation
def export_table(request):
    table = LaundryBillTable(LaundryBill.objects.all().order_by('-id'))
    table.paginate(page=request.GET.get("page", 1), per_page=15)
    RequestConfig(request).configure(table)

    export_format = request.GET.get("_export", None)
    if TableExport.is_valid_format(export_format):
        exporter = TableExport(export_format, table)
        return exporter.response("table.{}".format(export_format))

    return render(request, "laundry/export_table.html", {"table": table})

# Create your views here.
def laundrypage(request):
    # billtable = LaundryBillTable(LaundryBill.objects.all().order_by('-id'), template_name="django_tables2/bootstrap4.html")
    billtable = LaundryBillTable(LaundryBill.objects.filter(returns=False).order_by('-id'))
    billtable.paginate(page=request.GET.get("page", 1), per_page=5)
    # canceledbill = LaundryBillTable(LaundryBill.objects.filter(returns=True).order_by('-id'))
    # canceledbill.paginate(page=request.GET.get("page", 1), per_page=3)
    # print(str(billtable))
    return render(request, "laundry/laundry.html", {
                                                    'billtable':billtable,
                                                    # 'returnstable':canceledbill,
                                                    })


def get_single_field(request, bill):
    table = LaundryDataTable(LaundryData.objects.filter(bill=bill).order_by('-id'))
    single_field = LaundryData.objects.filter(bill=bill).first()
    # query = LaundryData.objects.values('bill').annotate(dcount=Count('bill'))
    single_form = LaundryDataForm(request.POST or None, instance=single_field)
    # billfield = request.POST.get('bill')
    if single_form.is_valid():
        instance = single_form.save()
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())#('/laundry/')
    context = {
        'form':single_form,
        'single_field':single_field,
        'table':table,
    }
    return render(request, 'laundry/single_field.html', context)

def pass_data(request, bill, customer, ltype, quantity, price, total):
    table = LaundryDataTable(LaundryData.objects.filter(bill=bill).order_by('-id'))
    form = LaundryDataForm(data={
                            'bill':bill,
                            'customer':customer,
                            'launtype':ltype,
                            'quantity':quantity,
                            'price':price,
                            'total':total,
                            })
    # if form.is_valid():
    #     form.save()
        # return HttpResponseRedirect('/laundry/additem/') 
    return render(request, 'laundry/laundry.html', {'form2':form,
                                                    'table':table})

def laundry_data(request, bill, **kwargs):
    # id_bill = kwargs.get('id')
    # iditem = kwargs.get('id')
    # This for make right redirect
    addbill = LaundryBill.objects.get(id=bill)
    editbill_data = LaundryBill.objects.get(id=bill)
    print(editbill_data)
    table = LaundryDataTable(LaundryData.objects.filter(bill=bill).order_by('-id'))
    query = LaundryData.objects.filter(bill=bill).first()
    qs = LaundryData.objects.values('customer').filter(bill=bill).first()
    qs1 = LaundryData.objects.filter(bill=bill)#values('customer').filter(bill=bill).last()
    
    print(editbill_data, qs, qs1)
    # qus = LaundryData.objects.raw('SELECT customer FROM laundry_LaundryData WHERE bill=%s' % bill)
    
    customer_name = request.POST.get('customer') 
    # bill_no = request.POST.get('bill') 
    match = LaundryData.objects.filter(customer=customer_name).exists() 
    print(', m = '+ str(match))
    if qs == None: # for avoid None exception
        bound_form = LaundryDataForm(data={'bill': editbill_data, 'customer':''})
    else:
        bound_form = LaundryDataForm(data={'bill': editbill_data, 'customer':qs['customer']})
     
    if request.method == 'POST':
        form = LaundryDataForm(request.POST or None)
        # form2 = LaundryDataForm(request.POST or None)
        if form.is_valid():  
            launtype = request.POST.get('launtype')
            quantity = request.POST.get('quantity')
            price = request.POST.get('price')
            total = request.POST.get('total')
            customer_name = request.POST.get('customer')
            bill_no = request.POST.get('bill')
            match = LaundryData.objects.filter(customer=customer_name, bill=bill_no).exists() 
            check_bill = LaundryData.objects.filter(bill=bill).exists()
            # data = request.POST.copy()
            # newitems(request)
            pass_data(request, bill_no, customer_name, launtype, quantity, price, total)
            if check_bill: # checking for (Bill ID)   
                if match:  # editbill_data == bill and customer_name == qs['customer']
                    instance = form.save()
                    instance.save()
                    return HttpResponseRedirect(instance.get_absolute_url())#('/laundry/')
                else:
                    raise Http404('You ar trying to insert wrong Bill ID or Customer ID, '+\
                                    'Bill ID is {}'.format(str(bill))) 
                                    #' and Customer ID is {}'.format(str(qs['customer'])))
            else:
                if request.method == 'POST':
                    form = LaundryDataForm(request.POST or None)
                    if form.is_valid():
                        form.save()
                        return HttpResponseRedirect(reverse('laundry:data', kwargs={'bill': bill})) 
                #

laundry/templates/laundry/export_table.html
{% extends 'laundry/index.html' %} {% load crispy_forms_tags %}{% load bootstrap %} {% load static %}
{% load render_table from django_tables2 %}
{% load querystring from django_tables2 %}
{% block content %}

<head>
    <title>Laundry</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/tables.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/jquery-ui.min.css' %}">
    {% comment %} <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> {% endcomment %}
    {% comment %} <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> {% endcomment %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
<a href="{% querystring '_export'='tsv' %}">Download TSV</a><br />

<a href="{% querystring '_export'='yaml' %}">Download YAML</a><br />

<a href="{% querystring '_export'='latex' %}">Download LATEX</a><br />

<a href="{% querystring '_export'='ods' %}">Download ODS</a><br />

<a href="{% querystring '_export'='xlsx' %}">Download XLSX</a><br />

<a href="{% querystring '_export'='json' %}">Download JSON</a><br />

<a href="{% querystring '_export'='csv' %}">Download CSV</a>

<a href="{% querystring '_export'='xlsx' %}">Download XLSX</a>
<form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'laundry:search' %}" hidden>
    <input class="form-control mr-sm-2" type="text" name='q' placeholder="Search" value="{{request.GET.q}}" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
<br />
{% if user.is_authenticated %} 
    {% if table %}
        <div >
            {% for format in table.export_formats %}
                <a href="{% querystring '_export'=format %}">
                    download  <code>.{{ format }}</code>
                </a>
            {% endfor %}
            {% comment %} {% export_url "csv" %} {% endcomment %}
            
            {% comment %} {% for format in view.export_formats %}
                <a href="{% export_url format %}">
                    download  <code>.{{ format }}</code>
                </a>
            {% endfor %} {% endcomment %}
            {% render_table table %}

        </div>
    {% comment %} {% elif table_search %}
        <div >
            {% render_table table_search %}
        </div> {% endcomment %}
    {% endif %}
    <br />

{% else %}
    <div class="container" style="inline:block;">
        <br />
        <br />
    </div>
    <div class="container">
        <tr>
            <td colspan="1">
                <form class="well form-horizontal" style="background-color:white">
                    <fieldset>
                        <br />
                        <p><strong>You must login in order to continue</strong></p><br>
                    </fieldset>
                </form>
            </td>
        </tr>
    </div>
    <br>
{% endif %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
<script >

</script>

{% endblock %}

laundry/templates/laundry/laundry.html
{% extends 'laundry/index.html' %} {% load crispy_forms_tags %}{% load bootstrap %} {% load static %}
{% load render_table from django_tables2 %}
{% block content %}

<head>
    <title>Laundry</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/tables.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/jquery-ui.min.css' %}">
    {% comment %} <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> {% endcomment %}
    {% comment %} <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> {% endcomment %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</head>
    
    {% comment %} <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'laundry:search' %}" hidden>
        <input class="form-control mr-sm-2" type="text" name='q' placeholder="Search" value="{{request.GET.q}}" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> {% endcomment %}
{% comment %} {% endif %} {% endcomment %}
    <br />
{% if user.is_authenticated %}
   {% comment %} <div class="container"> {% endcomment %}
    {% comment %} <div class="container"> {% endcomment %}
            {% comment %} <div class="floatLeft" style="float:left;"> {% endcomment %}
        {% comment %} <div class="row">
            <div class="col-4 ml-auto"> {% endcomment %}
                {% comment %} <form action="/laundry/bill/" method="POST" name="form">{% csrf_token %} {% endcomment %}
                    {% comment %} {{ query.get_absolute_url }}"/laundry/bill/" {% url 'laundry:data' bill=pk %} {% endcomment %}
                    {% comment %} <input type="text" class="form" name="recieveDate" placeholder="Recieve Date"/><br><br>
                    <input type="text" class="form" name="endDate" placeholder="End Date"/><br><br>
                    <input type="text" class="form" name="sumtotal" placeholder="Sum Total"/><br><br>
                    <input type="text" class="form" name="paid" placeholder="Paid"/><br><br>
                    <input type="text" class="form" name="remain" placeholder="Remain"/><br><br>
                    <input type="text" class="form" name="client" placeholder="Client Name"/><br><br>
                    <input type="submit" class="btn-primary" value="Submit"/>             
                                
                </form> 
            </div> {% endcomment %}
        {% comment %} </div> 
    </div> {% endcomment %}
    {% comment %} {% if table %}  {% endcomment %}
    <br />
    <br />
    {% if billtable %}
        <div >
            {% render_table billtable %}
        </div>
    {% elif day_table %}
        <a class="float-left btn btn-outline-primary" role="button" href="#print_day_report">Print Day Report</a>
        <div class="float-right">
            <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'laundry:search_date' %}">
                <input class="form-control mr-sm-2" type="text" placeholder="Search Date From" value="{{request.GET.f}}" name="f">
                <input class="form-control mr-sm-2" type="text" placeholder="Search Date To" value="{{request.GET.t}}" name="t">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div><br/><br/>
        <div >
            {% render_table day_table %}
        </div>
    {% elif date_table_search %}
        <div class="float-right">
            <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'laundry:search_date' %}">
                <input class="form-control mr-sm-2" type="text" placeholder="Search Date From" value="{{request.GET.f}}" name="f">
                <input class="form-control mr-sm-2" type="text" placeholder="Search Date To" value="{{request.GET.t}}" name="t">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div><br/><br/>
        <div >
            {% render_table date_table_search %}
        </div>
    {% elif zero_table %}
        <div >
            {% render_table zero_table %}
        </div>
    {% elif remain_table %}
        <div >
            {% render_table remain_table %}
        </div>
    {% elif table_sum %}
        <div >
            {% render_table table_sum %}
        </div>
    {% elif zero_remain_table %}
        <a class="float-right btn btn-primary" href="{% url 'laundry:GeneratePdf' %}" role="button">Print</a>
        <h1 class="float-left">{{ zero_remain_tag }} </h1><br/>
        <div >
            {% render_table zero_remain_table %}
        </div>
    {% elif returnstable %}
        <h1>All Canceled Bills</h1>
        <div >
            {% render_table returnstable %}
        </div>
    {% elif table %}
        <div >
            {% render_table table %}
        </div>
    {% elif table_search %}
        <div >
            {% render_table table_search %}
        </div>
    {% endif %}
    <br />
    {% if form %} 
        {% comment %} {% render_table table %} {% endcomment %}
        <div class="floatRight" style="float:left;">
            <form method="POST">{% csrf_token %}  
                <div id="f-newitems">
                    
                    {{ form.launtype.label_tag }} {{ form.launtype }}
                    {{ form.quantity.label_tag }} {{ form.quantity }}
                    {{ form.price.label_tag }} {{ form.price }}
                    {{ form.total.label_tag }} {{ form.total }}
                    {{ form.customer.label_tag }} {{ bound.customer }}
                    {{ form.bill.label_tag }} {{ bound.bill }}
                                        
                    <br />
                    <input type="submit" class="btn btn-primary" value="Add" id=""/>             
                    {% comment %} {% if editbill_data %}
                        <a href="{{ editbill_data.get_url_by_id }}" class="btn btn-primary"/>Edit Bill Data</a>
                    {% elif editbill %}
                        <a href="{{ editbill.get_url_by_id }}" class="btn btn-primary"/>Edit Bill</a>
                    {% endif %}
                    {% if  query %}
                        <a href="{% url 'laundry:edit_items' bill=query.bill id=query.id %}" class="btn btn-primary"/>Go To Bill and ID</a>
                    {% endif %} {% endcomment %}
                    {% comment %} <a href="{% url 'laundry:edit_bills' id=query.bill%}" class="btn btn-primary"/>Go To Edit Bill after</a>
                    <a href="{{ item_id.get_url_by_bill_and_id }}" class="btn btn-primary"/>Go To Bill and ID after</a> {% endcomment %}
                </div>
            </form>
        </div>
        <br />
    {% elif form2 %}
        <div class="floatRight" style="float:left;">
            <form method="POST" action='/laundry/additem/' id="f2">{% csrf_token %}  
                <div id="f-newitems">
                    {% for field in form2 %}
                        <div class="fieldWrapper">
                            {{ field.errors }}
                            {{ field.label_tag }} {{ field }}
                        </div>
                    {% endfor %}
                    <br />
                    <input type="submit" class="btn btn-primary" value="Add First Item" id=""/>
                    <br />
                </div>
            </form>
        </div>
        <br />
    {% endif %}
    
  
{% else %}
    <div class="container" style="inline:block;">
        <br />
        <br />
    </div>
    <div class="container">
        {% comment %} <table class="table table-striped">
            <tbody id="tbody-id"> {% endcomment %}
                <tr>
                    <td colspan="1">
                        <form class="well form-horizontal" style="background-color:white">
                            <fieldset>
                                <br />
                                <p><strong>You must login in order to continue</strong></p><br>
                            </fieldset>
                        </form>
                    </td>
                </tr>
            {% comment %} </tbody>
        </table> {% endcomment %}
    </div>
    <br>
{% endif %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
<script >
    {% comment %} if (document.getElementById("f2")){
        function processUser(){
            var parameters = location.search.substring(1).split("&");
            var temp = parameters[0].split("=");
            l = unescape(temp[1]);
            temp = parameters[1].split("=");
            p = unescape(temp[1]);
            document.getElementById("price").innerHTML = l;
            document.getElementById("customer").innerHTML = p;
        }
    }; {% endcomment %}
    
// 
{% comment %} var value1=document.getElementById("price").innerHTML;
var value2=document.getElementById("customer").innerHTML;
var queryString = "?para1=" + value1 + "&para2=" + value2;
window.location.href = "laundry/laundry.html" + queryString;

//
var queryString = decodeURIComponent(window.location.search);
queryString = queryString.substring(1);
var queries = queryString.split("&");
for (var i = 0; i < queries.length; i++)
{
  document.write(queries[i] + "<br>");
} {% endcomment %}
</script>

{% endblock %}