Project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
# import forms_builder.forms.urls
from django.conf import settings
from django.conf.urls.static import static
from jobs import views  # jobs.views
from accounts import views  # accounts.views
from crm.views import MainPage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPage.as_view(), name='mainpage'),
    # path('forms/', include(forms_builder.forms.urls)),
    path('crm/', include('crm.urls', namespace='KMA_CRM')),
    path('blog/', include('blog.urls', namespace='blog')),
    # path('signup/', include('accounts.urls', namespace='accounts')),
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('jobs/', include('jobs.urls', namespace='amr_jobs')),
    path('laundry/', include('laundry.urls', namespace='laundry')),
    path('amrblog/', include('amrblog.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #\
  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from crm import views
from crm.views import *  # HomePage,Search,SaveDone

app_name = "crm"
urlpatterns = [
    path('', views.HomePage, name='home'),
    path('results/', views.Search, name='search'),
    path('registerdata/', views.RegisterData, name='regdata'),
    path('done/', views.SaveDone, name='done'),
    # path('reports/', views.ClientsRport, name='clientreport'),
    path('reports/', ClientsRport.as_view(), name='clientreport'),
    # path('clients/', ClientsListView.as_view(), name='clients'),
    path('clients/edit/', views.EditClients, name='clients_edit'),
    # path('clients/edit/<int:id>/', views.ClientID, name='clients_update'),
    path('clients/edit/<int:id>/',
                views.ClientID, name='clients_update'),
    path('clients/', views.ClientName, name='clients'),
    # path('login/', views.LoginForm, name='login'),
    # path('signup/', views.signup, name='signup'),
    # path('register/', views.user_register, name='user_register'),
    path('record/', views.Firm, name='record_firm'),
    path('record/edit/', views.EditFirm, name='edit'),
    path('record/<int:id>/', views.Firm_Update, name='firm_update'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/models.py
from django.db import models
from django.urls import reverse
# from django.contrib.admin import widgets
# from datetime import datetime
# from django.utils import timezone
# from django.utils.timezone import now

# Create your models here.
class Registration(models.Model):

    name = models.CharField(max_length=150)
    username = models.CharField(max_length=50)
    email = models.EmailField(blank=True, max_length=254)
    password = models.CharField(max_length=50)
    bio = models.TextField(blank=True)

#this class for
# class Choices(models.Model):
#       description = models.CharField(max_length=100)

class Clients(models.Model):
    # record   = models.ForeignKey(RecordFirm, on_delete=models.CASCADE)
    name       = models.CharField(max_length=200)
    phone      = models.CharField(max_length=20, blank=True, null=True)
    mobile     = models.CharField(max_length=20, blank=True, null=True)
    address    = models.CharField(max_length=200, blank=True, null=True)
    photo      = models.ImageField(upload_to='Clients_pics', blank=True)
    identityNo = models.CharField(max_length=200, blank=True, null=True)
    notes      = models.CharField(max_length=2000, blank=True, null=True)

    def __str__(self):
        return self.name #+ " | " + str(self.photo)

    def get_absolute_url(self):
        return reverse('crm:clients_update', kwargs={'id': self.id})

    def goto_home(self):
        return reverse('crm:home')


class RecordFirm(models.Model):
    #now = timezone.now()
    Currency = (
        ('EGY', 'Egy Pound'),
        ('USD', 'US Dollar')
    )

    # Tax_Choice = ('taxno', 'Tax No.')
    # Part_Choice=('partno', 'Part No.')
    # Purchase_Choice=('purchaseno', 'Purchase No.')
    client_id   = models.ForeignKey(Clients,
                                    on_delete=models.CASCADE,
                                    default=False,
                                    null=False)
    firm_name   = models.CharField(max_length=200,
                                blank=True,
                                null=True,
                                name='Company Name')  # name= 'Company Name'
    manager     = models.CharField(max_length=200, blank=True, null=True)
    repres_name = models.CharField(max_length=200, blank=True, null=True)
    last_visit  = models.DateField()
    notes       = models.TextField()
    type        = models.CharField(max_length=3, choices=Currency, null=True)
    #paper       = models.ManyToManyField(Choices)
    tax_no      = models.BooleanField(default=False)
    part_no     = models.BooleanField(default=False)
    purchase_no = models.BooleanField(default=False)
    # client_id   = models.

    def __str__(self):
        return self.client_id

    def get_url(self):
        return reverse('crm:firm_update', kwargs={'id': self.id})

    def go_home(self):
        return reverse('crm:regdata') # , kwargs={'id': self.id}

crm/views.py
import io
from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.shortcuts import get_object_or_404, redirect, render, render_to_response
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django_tables2.paginators import LazyPaginator
from django.urls import reverse
from django.contrib.auth import authenticate, login

from django.contrib.auth.forms import UserCreationForm
from .forms import ClientsForm, RecordForm, RegisterForm
from django.contrib.auth.models import User
from django.db.models import Q
from .models import Clients, RecordFirm, Registration
from django.views.generic import TemplateView, ListView
from django_tables2 import SingleTableView
from .tables import ClientsTable
from reportlab.pdfgen import canvas
from django.views.generic.edit import FormMixin
# from crm.reports import MyReport

# Create your views here.
class MainPage(TemplateView):
    template_name = 'crm/mainpage.html'

class ClientsRport(SingleTableView):
    model = Clients
    table_class = ClientsTable
    template_name = "crm/report.html"
    pagination_class = LazyPaginator
    context_object_name = 'queryset'
    def get_query(self):
        queryset = ClientsTable(Clients.objects.all())
        return queryset

# def ClientsRport(request):
#     table = ClientsTable(Clients.objects.all().order_by('-id'))
#     table.paginate(page=request.GET.get("page", 1), per_page=5)
#
#     return render(request, "crm/report.html",
#                            {"table": table,})

# class ClientsListView(FormMixin, SingleTableView):
    # model = Clients
    # table_class = ClientsTable
    # # fields = ('__all__')
    # form_class = ClientsForm
    # template_name = "clients.html"  # "crm/report.html"
    # success_url = "/crm/"

    # def get_queryset(self):
    #     query = self.request.GET.get('q')
    #     if query:
    #         object_list = self.model.objects\
    #         .filter(Q(name__icontains=query)| Q(mobile__icontains=query))
    #     else:
    #         object_list = self.model.objects.none()
    #     return object_list
    #
    # def get_success_url(self):
    #     """Return the URL to redirect to after processing a valid form."""
    #     if not self.success_url:
    #         raise ImproperlyConfigured("No URL to redirect to. Provide a success_url.")
    #     return str(self.success_url)  # success_url may be lazy
    #
    # def get_form_class(self):
    #     """Return the form class to use."""
    #     return self.form_class
    #
    # def get_initial(self):
    #     """Return the initial data to use for forms on this view."""
    #     return self.initial.copy()
    #
    # def get_prefix(self):
    #     """Return the prefix to use for forms."""
    #     return self.prefix
    #
    # def get_form_kwargs(self):
    #     """Return the keyword arguments for instantiating the form."""
    #     kwargs = {
    #         'initial': self.get_initial(),
    #         'prefix': self.get_prefix(),
    #     }
    #     if self.request.method in ('POST', 'PUT'):
    #         kwargs.update({
    #             'data': self.request.POST,
    #             'files': self.request.FILES,
    #         })
    #     return kwargs
    #
    # def get_form(self, form_class=None):
    #     """Return an instance of the form to be used in this view."""
    #     if form_class is None:
    #         form_class = self.get_form_class()
    #     return form_class(**self.get_form_kwargs())
    #
    # def get_context_data(self, **kwargs):
    #     """Insert the form into the context dict."""
    #     if 'form' not in kwargs:
    #         kwargs['form'] = self.get_form()
    #     return super().get_context_data(**kwargs)
    #
    # def form_valid(self,form):
    #     super(ClientsListView,self).form_valid(form)
    #     # Add action to valid form phase
    #     messages.success(self.request, 'Item created successfully!')
    #     return HttpResponseRedirect(self.get_success_url())
    #
    # def form_invalid(self,form):
    #     # Add action to invalid form phase
    #     return self.render_to_response(self.get_context_data(form=form))

def HomePage(request):
    query = Clients.objects.all().order_by('-id')
    # qu_rg = RecordFirm.objects.all().order_by('-last_visit')

    paginator = Paginator(query, 5) # Two post per page
    page = request.GET.get('page')
    # search = Clients.objects.filter()
    try:
        cl_data = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        cl_data = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        cl_data = paginator.page(paginator.num_pages)

    context = {'query':query,
                'page':page,
                'cl_data':cl_data,
                # 'search':search,
              }
    return render(request, 'list.html', context)
    # return HttpResponse("<h2><p>Hello to our CRM APP.</p></h2>")

def Search(request):
    _search = request.GET.get('q')
    if _search:
        results = Clients.objects.order_by('-id')\
                 .filter(Q(name__icontains=_search)\
                 | Q(phone__icontains=_search)\
                 | Q(mobile__icontains=_search))
        # results = Clients.objects.filter(name__search=query)
    else:
        results = Clients.objects.all().order_by('-id')


    paginator = Paginator(results, 5) # One result per page
    page = request.GET.get('page')
    try:
        search_result = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        search_result = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        search_result = paginator.page(paginator.num_pages)

    context={ 'search_res':search_result,
              'page':page,
              'results':results,
            }

    return render(request, 'tables.html', context)

# def LoginForm(request):
#     return render(request, 'index.html')
#

def RegisterData(request):
    # query = Clients.objects.order_by('-id')
    regdata = RecordFirm.objects.all().order_by('-id')
    paginator = Paginator(regdata, 3) # one post per page
    page = request.GET.get('page')
    # search = Clients.objects.filter()
    try:
        reg_data = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        reg_data = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        reg_data = paginator.page(paginator.num_pages)
    context = {
        'data':regdata,
        'reg_data':reg_data,
        'page':page,
    }
    return render(request, 'list.html', context)
    # return HttpResponse("<h2><p>Hello to our CRM APP.</p></h2>")


def SaveDone(request):
    message = 'Saving Done Successfully'
    # images  = '/crm/img/crm1.jpeg'
    context = {
        'message':message, #'images':images,
    }
    return render(request,'savedone.html', context)


def EditFirm(request):
    # client = Clients.objects.order_by('-id')
    recordfirm = RecordFirm.objects.order_by('-id')
    context= {
        # 'client':client,
        'recordfirm':recordfirm,
    }

    return render(request, 'tables.html', context)


def signup(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/done')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def Firm(request): # Saving registration
    # rec = RecordFirm.objects.order_by('-id')
    if request.method == "POST":
        form = RecordForm(request.POST or None)
        if form.is_valid():
            instance = form.save()
            instance.save()
            # return redirect('/record/edit/')
            return HttpResponseRedirect(instance.get_url())
    else:
        form = RecordForm()


    context = {
        'form':form,
        'btn':'Save',
    }

    return render(request,'forms.html', context) #forms.html


def Firm_Update(request, id):
    # client = Clients.objects.get(id=id)
    instance = RecordFirm.objects.get(id=id)
    # recField = RecordFirm.objects.order_by('-id')
    form = RecordForm(request.POST or None, instance=instance)

    if form.is_valid():
        instance = form.save()
        instance.save()
        return HttpResponseRedirect(instance.get_url())

    context = {
        'instance':instance,
        # 'recField':recField,
        'form':form,
        'btn':'Update',
    }

    return render(request,'forms.html', context) #forms.html

# To assign client name when client id changed
# def GoToId(request):
#     # client = Clients.objects.last()
#     # client = Clients.objects.latest("id")
#     client = RecordFirm.objects.latest('client_id') #
#     # client = RecordFirm.objects.get(id=56)
#     #cl_id = client.id
#
#     form = RecordForm(request.GET or None, instance=client)
#     if form.is_valid():
#         instance = form.save()
#         instance.save()
#         # return HttpResponseRedirect(instance.get_url())
#
#     context = {
#         'client':client,
#         # 'cl_id':cl_id,
#         'form':form,
#         'equal':'=',
#     }
#     return render(request, 'forms.html', context)


def EditClients(request):
    client = Clients.objects.order_by('-id')
    # recordfirm = RecordFirm.objects.all()
    context= {
        'client':client,
        # 'rec':recordfirm,
    }
    return render(request, 'tables.html', context)


def ClientID(request, id): # update form , (request, id, name, phone, address)

crm/templates/clients.html
{% extends 'index.html' %} {% load crispy_forms_tags %} {% load bootstrap %} {% load static %} {% block content %}

<head>
    <!-- <title>Record Company</title> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

{% if user.is_authenticated %}

<!-- <div id="clear">
    <img src="{% static 'crm/img/crm1.jpeg' %}" alt="Logo" height="1000" width="1200">
</div> -->
<div class="container" id='div-f-cl'>
     <form method="post" enctype="multipart/form-data"> <!--#action="{% url 'crm:home' %}" -->
        {% csrf_token %}
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{ comp }}</div>
                <div class="panel-body">
                    <!-- {% if error_message %}
                    <p class="bg-danger p-d ml-b">{{ error_message }}</p>
                    {% endif %} -->
                    {{ form|crispy}}
                    <button type="submit" class="btn btn-primary" id="saveclients">{{ btn }}</button>
                    <!--  -->
                    <!-- <a class="btn btn-primary" href="{% url 'crm:clients_edit' %}">Table</a> -->
                    <!-- <a class="btn btn-primary" href="{% url 'crm:clients' %}">{{ New }}</a> -->
                    <!-- <button type="submit" class="btn btn-primary" id="">{{ btn }}</button> -->
                    {% if instance %}
                    <a class="btn btn-primary" href="{% url 'crm:clients' %}" id="saveclients">{{ New }}</a>

                    <!-- <a class="btn btn-primary" href="{{ instance.get_ID }}">Go To ID</a> -->
                    <a class="btn btn-primary" href="{{ instance.goto_home }}" id="gotohome">Go To Home</a>
                    {% else %}

                    <a class="btn btn-primary" href="{% url 'crm:home' %}" id="gotohome">{{ New }}</a> {% endif %}

                    <!-- <div class="form-group clearfix">
                        <label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Username<span class="text-red">*</span>:</label>
                        <div class="col-md-6">
                            {{ form.record }}
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-right">Email<span
                                class="text-red">*</span>:</label>
                        <div class="col-md-6">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
                        <div class="col-md-6">
                            {{ form.phone }}
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-right">Confirm password:</label>
                        <div class="col-md-6">
                            {{ form.address }}
                        </div>
                    </div> -->
                    <!-- <div class="form-group clearfix">
                        <label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-right">First
                            Name:</label>
                        <div class="col-md-6">
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-right">Last
                            Name:</label>
                        <div class="col-md-6">
                            {{ form.last_name }}
                        </div>
                    </div>
                    <div class="form-group clearfix">
                        <label for="{{ form.phone_number.id_for_label }}" class="col-md-4 control-label text-right">Phone Number:</label>
                        <div class="col-md-6">
                            {{ form.phone_number }}
                        </div>
                    </div> -->
                    <!-- <div class="col-md-6 col-md-offset-4"> -->
                    <!-- <input type="submit" value="Add" class="btn btn-success"> -->
                    <!-- <button type="submit" class='btn btn-outline-primary'>Add</button> -->

                    <!-- </div> -->
                </div>
            </div>
        </div>
    </form>
</div>

{% comment %} {% else %}
<br>
<div class="container">
    <table class="table table-striped">
        <tbody id="tbody-id">
          <tr>
            <td colspan="1">
              <form class="well form-horizontal" style="background-color:white">
                <fieldset>
                <br>
                    <p><strong>You must login in order to continue</strong></p><br>
                </fieldset>
              </form>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <br> {% endcomment %}

{% endif %}
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- </div> -->
{% endblock %}

crm/templates/clients_edit.html
{% extends 'index.html' %} {% load static %} {% block content %}

<head>
    <!-- <title>Record Company</title> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<!-- <div id="clear">
    <img src="{% static 'crm/img/crm1.jpeg' %}" alt="Logo" height="1000" width="1200">
</div> -->
<div class="container" id='div-f-cl'>
    <!-- <form method="post"> -->
    <!-- {% csrf_token %} -->
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">Clients</div>
            <div class="panel-body">

                <!-- <button type="submit" class="btn btn-primary" id="">Add</button> -->
                <a class="btn btn-primary" href="{% url 'crm:clients_edit' %}">Table</a>
                <!-- <a class="btn btn-primary" href="{{ client.get_absolute_url }}">Edit</a> -->

                <p>{{clients.id}}</p>
                <p>{{cliens.name}}</p>
                <p>{{clients.phone}}</p>
                <p>{{clients.address}}</p>
                <a class="btn btn-primary" href="{% url 'crm:clients_edit' %}">Edit</a>
                <!-- <a class="btn btn-primary" href="{{ cl.get_absolute_url }}">Edit</a> -->

            </div>
        </div>
    </div>
    <!-- </form> -->
</div>

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- </div> -->
{% endblock %}

crm/templates/savedone.html
{% extends 'index.html' %} {% load crispy_forms_tags %} {% load bootstrap %} {% load static %} {% block content %}

<head>
    <!-- <title>Record Company</title> -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'ss/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<div id='save'>
    <h1>
        <p id="psave">{{message}}</p>
    </h1>
</div>
<div id="image">
    <img src="{% static '/crm/img/crm1.jpeg' %}" alt="Logo" height="1000" width="1200">
</div>
<!-- <img src="static/crm/img/"> -->

<!-- <div id="clear"></div> -->
<!-- <div style="clear: both" id="clear"></div> -->

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- </div> -->
{% endblock %}

crm/templates/tables.html
{% extends 'index.html' %} 
{% load bootstrap %} {% load static %} {% block content %}

<head>
    <title>Reports</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/tables.css' %}">
    <link rel="stylesheet" href="{% static 'css/pagination.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<span>
  <h2 style="color:DarkGreen;">Clients Table</h2>
</span>
<!-- <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'crm:search' %}">
    <input class="form-control mr-sm-2" type="text" name='q' placeholder="Search Clients" value="{{request.GET.q}}" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form> -->
<div class="container" id='div-table'>
  {% include "crm/pagination.html" with page=search_res %}
  <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'crm:search' %}" hidden>
      <input class="form-control mr-sm-2" type="text" name='q' placeholder="Search Clients" value="{{request.GET.q}}" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   </form>
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
            <div class="panel-body">
                <div class="table-wrapper">
                  <table class="fl-table" id="table"> <!-- class="fl-table" -->
                      {% if client %}
                      <a class="btn btn-primary" href="{% url 'crm:clients' %}" id="btn-cl">Back</a>
                      <a class="btn btn-primary" href="{% url 'crm:home' %}" id="btn-cl">Go To ID</a>
                          <thead>
                            <tr>
                                <th>Client ID</th>
                                <th>Client Name</th>
                                <th>Phone No.</th>
                                <th>Mobile</th>
                                <th>Address</th>
                                <th>identity No</th>
                                <th>Notes</th>
                            </tr>
                        </thead>
                        {% for cl in client %}
                        <tbody>
                            <tr>
                                <td>{{cl.id}}</td>
                                <td>{{cl.name}}</td>
                                <td>{{cl.phone}}</td>
                                <td>{{cl.mobile}}</td>
                                <td>{{cl.address}}</td>
                                <td>{{cl.identityNo}}</td>
                                <td>{{cl.notes}}</td>
                            </tr>
                        </tbody>
                        {% endfor %}
                        {% elif recordfirm %}
                        <a class="btn btn-primary" href="{% url 'crm:record_firm' %}" id="btn-rec">Back</a>
                        <thead>
                            <tr>
                                <th scope="row">ID</th>
                                <th>Currency</th>
                                <th>Company Name</th>
                                <th>Manager</th>
                                <th>Representative</th>
                                <th>Last Visit</th>
                                <th>Notes</th>
                                <th>Taxation No.</th>
                                <th>Papers1</th>
                                <th>Papers2</th>
                            </tr>
                        </thead>
                        {% for rec in recordfirm %}
                        <tbody>
                            <tr>
                                <td>{{rec.id}}</td>
                                <td>{{rec.type}}</td>
                                <td>{{rec.firm_name}}</td>
                                <td>{{rec.manager}}</td>
                                <td>{{rec.repres_name}}</td>
                                <td>{{rec.last_visit}}</td>
                                <td>{{rec.notes}}</td>
                                <td>{{rec.tax_no}}</td>
                                <td>{{rec.part_no}}</td>
                                <td>{{rec.purchase_no}}</td>
                            </tr>
                        </tbody>
                        {% endfor %}
                        {% elif results %}
                        <a class="btn btn-primary" href="{% url 'crm:clients' %}" id="btn-cl">Back</a>
                        <a class="btn btn-primary" href="{% url 'crm:home' %}" id="btn-cl">Home</a>
                        <thead>
                              <tr>
                                  <th>Client ID</th>
                                  <th>Client Name</th>
                                  <th>Phone No.</th>
                                  <th>Mobile</th>
                                  <th>Address</th>
                                  <th>identity No</th>
                                  <th>Notes</th>
                               </tr>
                        </thead>
                            {% for cl in search_res %}
                            <tbody>
                                <tr>
                                    <td>{{cl.id}}</td>
                                    <td>{{cl.name}}</td>
                                    <td>{{cl.phone}}</td>
                                    <td>{{cl.mobile}}</td>
                                    <td>{{cl.address}}</td>
                                    <td>{{cl.identityNo}}</td>
                                    <td>{{cl.notes}}</td>
                                </tr>
                            </tbody>
                            {% endfor %}
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% include "crm/pagination.html" with page=search_res %}

    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

{% endblock %}