Project/urls.py
from django.contrib import admin
from django.urls import path, include, reverse
# import forms_builder.forms.urls
from django.conf import settings
from django.conf.urls.static import static
from jobs import views  # jobs.views
from accounts import views  # accounts.views
from crm.views import MainPage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPage.as_view(), name='mainpage'),
    # path('forms/', include(forms_builder.forms.urls)),
    path('crm/', include('crm.urls', namespace='KMA_CRM')),
    path('blog/', include('blog.urls', namespace='blog')),
    # path('signup/', include('accounts.urls', namespace='accounts')),
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('jobs/', include('jobs.urls', namespace='amr_jobs')),
    path('laundry/', include('laundry.urls', namespace='laundry')),
    path('amrblog/', include('amrblog.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #\
  # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
# import forms_builder.forms.urls

app_name='blog'

urlpatterns = [
    path('', views.allblogs, name='allblogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

crm/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from crm import views
from crm.views import *  # HomePage,Search,SaveDone

app_name = "crm"
urlpatterns = [
    path('', views.HomePage, name='home'),
    path('results/', views.Search, name='search'),
    path('registerdata/', views.RegisterData, name='regdata'),
    path('done/', views.SaveDone, name='done'),
    # path('reports/', views.ClientsRport, name='clientreport'),
    path('reports/', ClientsRport.as_view(), name='clientreport'),
    # path('clients/', ClientsListView.as_view(), name='clients'),
    path('clients/edit/', views.EditClients, name='clients_edit'),
    # path('clients/edit/<int:id>/', views.ClientID, name='clients_update'),
    path('clients/edit/<int:id>/',
                views.ClientID, name='clients_update'),
    path('clients/', views.ClientName, name='clients'),
    # path('login/', views.LoginForm, name='login'),
    # path('signup/', views.signup, name='signup'),
    # path('register/', views.user_register, name='user_register'),
    path('record/', views.Firm, name='record_firm'),
    path('record/edit/', views.EditFirm, name='edit'),
    path('record/<int:id>/', views.Firm_Update, name='firm_update'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobs/urls.py
from django.urls import path
from jobs import views

app_name='jobs'

urlpatterns=[
    path('', views.home, name='home'),
]

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
# class PublishedManager(models.Manager):
#     def get_queryset(self):
#         return super(PublishedManager,
#                     self).get_queryset()  #\
                    # .filter(id=1) ##
                    # .filter(status='published') ## Not in this version of Django
                    # .filter(body='My first Blog') ##
                    # .filter(id='My first Blog') ##
                    # .filter(image='My first Blog') ##
                    # .filter(title='My first Blog') ##

class Blog(models.Model):
    # objects = models.Manager() # The default manager.
    # published = PublishedManager() # Our custom manager.

    title = models.CharField(max_length=255)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:250]   #[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

    def get_absolute_url(self):
        return reverse('blog:detail', args=[blog_id])
    # From a "Django2 By Examples" Book
    # def get_absolute_url(self):
    #     return reverse('blog:post_detail',
    #                                     args=[self.publish.year,
    #                                     self.publish.month,
    #                                     self.publish.day,
    #                                     self.slug])

blog/forms.py
from django import forms
from .models import Blog


class BlogForm(forms.ModelForm):

    class Meta:
        model  = Blog
        fields = ('__all__')

blog/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from .models import Blog

# Create your views here.
def allblogs(request):
    # blogs = Blog.objects
    # blogs = Blog.published.filter(title__startswith='My')
    # return render(request, 'blog/allblogs.html', {'blogs':blogs})

    # object_list = Blog.published.all()
    object_list = Blog.objects.all()
    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        blogs = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        blogs = paginator.page(paginator.num_pages)
    return render(request,'blog/allblogs.html',
                          {'page': page,
                          'blogs': blogs})



def detail(request, blog_id):
    detailblog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':detailblog})

# def HomePage(request):
#     return HttpResponse('My Home Page')

blog/templates/blog/allblogs.html
<!-- extend from an index.html to make the style of thehome page of your project is the same in all Application -->
<!-- Or you have to create another index.html file for every app. to make it unique /[[[[]]]]-->
{% load bootstrap %} {% load static %}

<!doctype html>
<html lang="en">
  <head>
    {% load static %}
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Amr's Blog</title>

    <!-- Bootstrap core CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'jobs:home' %}">My Projects</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="http://github.com/cehceh">Github</a>
          <a class="nav-item nav-link" href="{% url 'jobs:home' %}" >My Projects</a>
          <a class="nav-item nav-link" href="{% url 'crm:home' %}" >Main App</a>
          <!-- <a class="nav-link disabled" href="{% static 'seven_habits.pdf' %}">Resume</a> -->
          <!-- <a class="nav-item nav-link active" id="blog-button" href="{% url 'blog:allblogs' %}">Blog</a> -->
        </div>
      </div>
    </nav>
  </header>

  <main role="main">
    <div class="container">

    <h1 class="text-center pt-3" id="welcome-message">Welcome to Amr's Blog</h1>
    <br />
    <br />
    <h2>Latest Posts</h2>
    <hr />

    {% for blog in blogs.all %}
    <a href="{% url 'blog:detail' blog.id %}"><h3>{{ blog.title }}</h3></a>
    {{ blog.pub_date_pretty }}
    <br />
    <img class="img-fluid" src="{{ blog.image.url }}" height=200 width=200 />
    <br />
    <p>{{ blog.summary }}</p>
    {% endfor %}

  </div>

  </main>

  <footer class="fixed-bottom">
    <div class="container text-center">
      <p>© Amr Aly {% now "Y" %}</p>
    </div>
  </footer>


  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  {% include "crm/pagination.html" with page=blogs %}

</body>
</html>

blog/templates/blog/comments.html
{% extends "amrblog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>



<!--  -->
{% with comments.count as total_comments %}
<h2>
{{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}
<!--  -->
{% for comment in comments %}
<div class="comment">
<p class="info">
Comment {{ forloop.counter }} by {{ comment.name }}
{{ comment.created }}
</p>
{{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There are no comments yet.</p>
{% endfor %}
<!--  -->
{% if new_comment %}
  <h2>Your comment has been added.</h2>
<!-- {% else %}
  <h2>Add a new comment</h2>
  <form action="{{ post.get_absolute_url }}" method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
  <p><input type="submit" value="Add comment"></p>
  </form> -->
{% endif %}
<!--  -->
<p>

blog/templates/blog/detail.html
<!doctype html>
<html lang="en">
<head>
  {% load staticfiles %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">


  <title>{{ blog.title }}</title>

  <!-- Bootstrap core CSS -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <!-- <a class="navbar-brand" href="{% url 'home' %}">Nick Walter</a> -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="http://twitter.com/nickchuckwalter">Twitter</a>
          <a class="nav-item nav-link" href="{% static 'resume.pdf' %}">Resume</a>
          <a class="nav-item nav-link active" href="{% url 'blog:allblogs' %}">Blog</a>
        </div>
      </div>
    </nav>
  </header>

  <main role="main">
    <div class="container">




    <h1 class="text-center pt-3">{{ blog.title }}</h1>
    <p class="text-center">{{ blog.pub_date }}</p>
    <img class="img-fluid" src="{{ blog.image.url }}"  />
    <br />
    <br />
    <p>{{ blog.body }}</p>


  </div>

  </main>

  <footer class="text-muted">
    <div class="container text-center">
      <p>© AMR AMMER {% now "Y" %}</p>
      </div>
  </footer>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

</body>
</html>